server:
  port: ${SERVER_PORT:8081}

spring:
  application:
    name: security-demo
#  redis:
#    host: localhost
#    port: 6379
#    password: abc123
#    database: 0
#    timeout: 1s
#    lettuce:
#      pool:
#        max-active: 8
#        max-idle: 8
#        min-idle: 0
#        max-wait: -1ms