server:
  port: ${SERVER_PORT:9096}

spring:
  application:
    name: oauth2-client-web

security:
  oauth2:
    client:
      client-id: client2
      client-secret: 123456
      user-authorization-uri: ${auth-server}/oauth/authorize
      access-token-uri: ${auth-server}/oauth/token
      registered-redirect-uri: http://www.baidu.com
      authorized-grant-types:
        - client_credentials
    resource:
      jwt:
        key-uri: ${auth-server}/oauth/token_key    #获得jwt加密公钥

auth-server: http://localhost:9090


