mybatis-plus:
  mapper-locations: classpath*:/mapper/*Mapper.xml
  configuration:
    default-enum-type-handler: com.baomidou.mybatisplus.extension.handlers.MybatisEnumTypeHandler

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    # MySQL在高版本需要指明是否进行SSL连接 解决则加上 &useSSL=false
    #    url: jdbc:mysql://127.0.0.1:3306/test?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF8&zeroDateTimeBehavior=convertToNull&useSSL=false
    url: jdbc:mysql://localhost:3306/sv?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: abc=123