mybatis-plus:
  mapper-locations: classpath*:/mapper/*Mapper.xml
  type-handlers-package: cn.jay.mybatis.type
  configuration:
    default-enum-type-handler: com.baomidou.mybatisplus.extension.handlers.MybatisEnumTypeHandler
    map-underscore-to-camel-case: true
    auto-mapping-unknown-column-behavior: warning
    cache-enabled: false

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    # MySQL在高版本需要指明是否进行SSL连接 解决则加上 &useSSL=false
    url: ${datasource.url:jdbc:mysql://localhost:3306/security_demo?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai}
    username: ${datasource.username:root}
    password: ${datasource.password:771229}

