server:
  port: ${SERVER_PORT:9091}

spring:
  application:
    name: oauth2-resource-server-demo
  profiles:
    include: mybatis

security:
  oauth2:
    resource:
      user-info-uri: http://localhost:9090/user/

config:
  #安全认证
  auth:
    ignoreUrls:
      - /api/system/user/getCurrentUserInfo
      - /index
      - /logout
      - /swagger-ui.html
      - /swagger-resources/configuration/ui
      - /swagger-resources
      - /v2/api-docs
      - /swagger-resources/configuration/security
      - /**/*.js
      - /**/*.css
      - /**/*.png
      - /**/*.ico