server:
  port: ${SERVER_PORT:9091}

spring:
  application:
    name: oauth2-resource-server-demo

security:
  oauth2:
    client:
      client-id: client1
      client-secret: 123456
    resource:
#      token-info-uri: http://localhost:9090/oauth/check_token
#      user-info-uri: http://localhost:9090/oauth/user/
      jwt:
        key-uri: http://localhost:9090/oauth/token_key

